### ISSUE TITLE
(doc ...) fails in InstaREPL - even for standard functions

### ISSUE THREAD

**Issue by peter-kehl** [oakes/Nightcode#240]
Hi Zach,

Thank you for Nightcode.

`(doc map)` fails in InstaREPL (but works in REPL window): `java.lang.RuntimeException: Unable to resolve symbol: doc in this context, compiling:(NO_SOURCE_PATH:0:0)`.

Nightcode 2.6.0 installed from RPM on SUSE x64. Does Nightcode include a JVM? If not, my JVM is Open JDK "11" 2018-09-25.

**Comment by peter-kehl** [comment]
When running Nightcode from a JAR, this is the error log in shell;
```
clojure.lang.ArityException: Wrong number of args (1) passed to: user/eval1920/fn--1921
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$print_sequential.invokeStatic(core_print.clj:53)
	at clojure.core$fn__7019.invokeStatic(core_print.clj:174)
	at clojure.core$fn__7019.invoke(core_print.clj:174)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.core$pr_on.invokeStatic(core.clj:3666)
	at clojure.core$pr.invokeStatic(core.clj:3669)
	at clojure.core$pr.invoke(core.clj:3669)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$pr_str.invokeStatic(core.clj:4702)
	at clojure.core$pr_str.doInvoke(core.clj:4702)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at nightcode.editors$form__GT_serializable.invokeStatic(editors.clj:29)
	at nightcode.editors$form__GT_serializable.invoke(editors.clj:26)
	at clojure.core$mapv$fn__8088.invoke(core.clj:6832)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$mapv.invokeStatic(core.clj:6823)
	at clojure.core$mapv.invoke(core.clj:6823)
	at nightcode.editors$eval_code.invokeStatic(editors.clj:132)
	at nightcode.editors$eval_code.invoke(editors.clj:128)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at nightcode.editors$editor_pane$reify__6492.oneval(editors.clj:170)
        ...
```
